### ISSUE TITLE
Argument for @NotNull parameter 'id' 

### ISSUE THREAD

**Issue by antoni-rokitnicki** [krasa/GrepConsole#101]
Version: 7.2.162.000.0

Argument for @NotNull parameter 'id' of com/intellij/execution/ui/layout/impl/RunnerLayoutUiImpl.createContent must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'id' of com/intellij/execution/ui/layout/impl/RunnerLayoutUiImpl.createContent must not be null
	at com.intellij.execution.ui.layout.impl.RunnerLayoutUiImpl.$$$reportNull$$$0(RunnerLayoutUiImpl.java)
	at com.intellij.execution.ui.layout.impl.RunnerLayoutUiImpl.createContent(RunnerLayoutUiImpl.java)
	at krasa.grepconsole.grep.OpenGrepConsoleAction.createGrepConsole(OpenGrepConsoleAction.java:93)
	at krasa.grepconsole.grep.PinnedGrepsReopener$1.initConsole(PinnedGrepsReopener.java:70)
	at krasa.grepconsole.grep.PinnedGrepsReopener$1.lambda$0(PinnedGrepsReopener.java:54)

**Comment by krasa** [comment]
IDE version? Does it always happen? Any idea how to reproduce it?

**Comment by antoni-rokitnicki** [comment]
2017.3.2

no idea, it just happens.

I feel that the biggest problem is that

@Nullable
protected String getContentType(@NotNull RunnerLayoutUi runnerLayoutUi) {

is Nullable, but

@NotNull
public Content createContent(@NotNull String id,

expect NotNull

is that id really imporant ? maybe you could pass any notNull value if method returns null ?

**Comment by krasa** [comment]
Well, it is kinda confusing, but I check in #update that it is not null, so it should not be null. 

I suspect there is some multithreading issue because it can also return wrong value - and then it puts the console into e.g. variables tab when debugging.

**Comment by krasa** [comment]
This should help, but will not work properly for things like "XSLT-Output" whatever that may be.
