### ISSUE TITLE
Tail console crashes

### ISSUE THREAD

**Issue by jerry1970** [krasa/GrepConsole#107]
Just installed the Grep Console, it looks like an amazing tool but when I first opened a grep window on a file I had a tail on, it crashed. Restarting PHPStorm didn't work.

I tried to set  a filter `*2018*` and got this error:

```
Cannot find content:*2018*
java.lang.IllegalArgumentException: Cannot find content:*2018*
	at com.intellij.ui.content.impl.ContentManagerImpl.setSelectedContent(ContentManagerImpl.java:464)
	at com.intellij.execution.ui.layout.impl.RunnerLayoutUiImpl.selectAndFocus(RunnerLayoutUiImpl.java:196)
	at com.intellij.execution.ui.layout.impl.RunnerLayoutUiImpl.selectAndFocus(RunnerLayoutUiImpl.java:189)
	at krasa.grepconsole.grep.OpenGrepConsoleAction.createGrepConsole(OpenGrepConsoleAction.java:100)
	at krasa.grepconsole.grep.PinnedGrepsReopener$1.initConsole(PinnedGrepsReopener.java:70)
	at krasa.grepconsole.grep.PinnedGrepsReopener$1.lambda$0(PinnedGrepsReopener.java:54)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.n(IdeEventQueue.java:779)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:720)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
My PHPStorm About:
```
PhpStorm 2018.1.1
Build #PS-181.4445.72, built on April 9, 2018
Licensed to ****
Subscription is active until ****
JRE: 1.8.0_152-release-1136-b27 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.13.0-38-generic
```

I realise this is not a lot of information. Is there anyhting I can do to give you more info?

**Comment by krasa** [comment]
Does it happen always or only sometimes? In a certain file or everywhere?

**Comment by jerry1970** [comment]
I set it to watch a node.js log file on a docker image. This happened every time.

**Comment by krasa** [comment]
Try the new version, it should help a little bit.

And could you post some screenshots?
