### ISSUE TITLE
Argument for @NotNull parameter 'runContentDescriptor' of krasa/grepconsole/grep/OpenGrepConsoleAction$PinAction.<init> must not be null

### ISSUE THREAD

**Issue by longzl2015** [krasa/GrepConsole#109]
Argument for @NotNull parameter 'runContentDescriptor' of krasa/grepconsole/grep/OpenGrepConsoleAction$PinAction.<init> must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'runContentDescriptor' of krasa/grepconsole/grep/OpenGrepConsoleAction$PinAction.<init> must not be null
	at krasa.grepconsole.grep.OpenGrepConsoleAction$PinAction.$$$reportNull$$$0(OpenGrepConsoleAction.java)
	at krasa.grepconsole.grep.OpenGrepConsoleAction$PinAction.<init>(OpenGrepConsoleAction.java)
	at krasa.grepconsole.grep.OpenGrepConsoleAction.createGrepConsole(OpenGrepConsoleAction.java:89)
	at krasa.grepconsole.grep.PinnedGrepsReopener$1.initConsole(PinnedGrepsReopener.java:70)
	at krasa.grepconsole.grep.PinnedGrepsReopener$1.lambda$0(PinnedGrepsReopener.java:54)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:779)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:720)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by krasa** [comment]
IntelliJ version, run configuration type?

**Comment by longzl2015** [comment]
1. Intellij veriosn: 
2018.1.3

2. run configuration:
Spring boot 
![wx20180515-132648](https://user-images.githubusercontent.com/12516505/40038420-9dd21b8e-5844-11e8-8970-ca34b58fac8a.png)


3. both debug mode & normal mode 

4. still running ?
When I right-click and click "GREP" , the plugin can't work. 
And show the Error message:
```
Argument for @NotNull parameter 'runContentDescriptor' of krasa/grepconsole/grep/OpenGrepConsoleAction$PinAction.<init> must not be null 
```

5.  I recently upgraded the idea version and the GrepConsole plugin

**Comment by longzl2015** [comment]
I reinstall the GrepConsole plugin, and It works well.

**Comment by krasa** [comment]
That's strange :)
