### ISSUE TITLE
GrepConsole is preventing running in 2018.2 EAP build 182.3208.17

### ISSUE THREAD

**Issue by mark-anders** [krasa/GrepConsole#111]
After upgrading to the new AppCode EAP, I'm not able to see any Console output. Below is  the stack trace from the error.  I downloaded the 8.0.162.000.1 version, but that did not fix it.  Disabling/Uninstalling it did.

```
java.lang.Throwable: Icon cannot be found in 'highlight.gif', aClass='class krasa.grepconsole.action.OpenConsoleSettingsAction'
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:123)
	at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:148)
	at krasa.grepconsole.action.OpenConsoleSettingsAction.<clinit>(OpenConsoleSettingsAction.java:15)
	at krasa.grepconsole.integration.GrepConsoleActionsPostProcessor.postProcess(GrepConsoleActionsPostProcessor.java:34)
	at com.intellij.execution.impl.ConsoleViewImpl.createConsoleActions(ConsoleViewImpl.java:1411)
	at com.intellij.execution.testframework.sm.runner.ui.SMTRunnerConsoleView.createTestResultsPanel(SMTRunnerConsoleView.java:78)
	at com.intellij.execution.testframework.ui.BaseTestsOutputConsoleView.initUI(BaseTestsOutputConsoleView.java:52)
	at com.intellij.execution.testframework.sm.runner.ui.SMTRunnerConsoleView.initUI(SMTRunnerConsoleView.java:86)
	at com.intellij.execution.testframework.sm.SMTestRunnerConnectionUtil.initConsoleView(SMTestRunnerConnectionUtil.java:138)
	at com.intellij.execution.testframework.sm.SMTestRunnerConnectionUtil.createConsole(SMTestRunnerConnectionUtil.java:90)
	at com.jetbrains.cidr.execution.CidrConsoleBuilder.createConsole(CidrConsoleBuilder.java:25)
	at com.jetbrains.cidr.execution.testing.unit.AppCodeOCUnitLauncher$1.createConsole(AppCodeOCUnitLauncher.java:105)
	at com.jetbrains.cidr.execution.testing.CidrTestCommandLineState.createConsole(CidrTestCommandLineState.java:77)
	at com.jetbrains.cidr.execution.testing.OCTestConsoleBuilder.createConsole(OCTestConsoleBuilder.java:40)
	at com.intellij.execution.filters.TextConsoleBuilderImpl.getConsole(TextConsoleBuilderImpl.java:48)
	at com.jetbrains.cidr.execution.OCConsoleBuilder.getConsole(OCConsoleBuilder.java:42)
	at com.intellij.execution.configurations.CommandLineState.createConsole(CommandLineState.java:91)
	at com.intellij.execution.configurations.CommandLineState.execute(CommandLineState.java:81)
	at com.jetbrains.cidr.execution.CidrCommandLineState.execute(CidrCommandLineState.java:42)
	at com.intellij.execution.runners.DefaultProgramRunnerKt.executeState(DefaultProgramRunner.kt:34)
	at com.intellij.execution.runners.DefaultProgramRunner.doExecute(DefaultProgramRunner.kt:28)
	at com.jetbrains.cidr.execution.AppCodeRunner.startSession(AppCodeRunner.java:86)
	at com.jetbrains.cidr.execution.AppCodeAppRunner.startSession(AppCodeAppRunner.java:31)
	at com.jetbrains.cidr.execution.AppCodeRunner.doExecute(AppCodeRunner.java:79)
	at com.intellij.execution.runners.GenericProgramRunner$execute$$inlined$runProfileStarter$1.executeAsync(GenericProgramRunner.kt:69)
	at com.intellij.execution.runners.GenericProgramRunnerKt$startRunProfile$$inlined$runProfileStarter$1.executeAsync(GenericProgramRunner.kt:69)
	at com.intellij.execution.impl.ExecutionManagerKtImpl$startRunProfile$startRunnable$1.run(ExecutionManagerKtImpl.kt:61)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:74)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.k(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:722)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by krasa** [comment]
Ah man, JetBrains fucked up loading of icons :(

**Comment by krasa** [comment]
new build is up

**Comment by oreineke** [comment]
Great, works fine now, thank!!!

**Comment by mark-anders** [comment]
Wow, that was fast!  Works great for me too.
