### ISSUE TITLE
Null Pointer Exception 

### ISSUE THREAD

**Issue by SteveSteinitz** [krasa/GrepConsole#124]
Hello,

Thank you for your work on this your very useful plugin.

I have a couple of grep console tabs that return even after I close them.  I forget they are there, but they may have something to do with the Null Pointer Exception that appears sometime around WebStorm launch, or maybe debug configuration launch.  

In any case, for what it's worth, here are the first few lines of the exception trace:

java.lang.NullPointerException at krasa.grepconsole.grep.OpenGrepConsoleAction.createGrepConsole(OpenGrepConsoleAction.java:97)
	at krasa.grepconsole.grep.PinnedGrepsReopener$1.initConsole(PinnedGrepsReopener.java:73)
	at krasa.grepconsole.grep.PinnedGrepsReopener$1.lambda$run$1(PinnedGrepsReopener.java:57)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)

I hope that's useful.  Let me know if I can do anything else.

All the best

**Comment by krasa** [comment]
for what kind of run configuration does it happen?

**Comment by SteveSteinitz** [comment]
Thanks for your reply, Vojtěch

It's a React-Native run configuration, usually running in 'debug' mode (i.e. after clicking the Debug button).  It's intermittent so probably tricky to debug.

Cheers
