### ISSUE TITLE
java.lang.AssertionError: Must be EDT

### ISSUE THREAD

**Issue by maierma** [krasa/GrepConsole#127]
In case you stop and remove a Docker container with the Docker plugin you get following exception:
```java
java.lang.AssertionError: Must be EDT
	at com.intellij.openapi.wm.impl.status.IdeStatusBarImpl.removeWidget(IdeStatusBarImpl.java:584)
	at krasa.grepconsole.stats.GrepConsoleStatusBarWidget.dispose(GrepConsoleStatusBarWidget.java:69)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:48)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:44)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:138)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:107)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:182)
	at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:107)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:126)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:107)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:182)
	at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:107)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:126)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:107)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:182)
	at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:107)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:126)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:107)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:182)
	at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:107)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeAll(ObjectTree.java:151)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:129)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:125)
	at com.intellij.remoteServer.impl.runtime.log.DeploymentLogManagerImpl.disposeLogs(DeploymentLogManagerImpl.java:133)
	at com.intellij.remoteServer.impl.runtime.ServerConnectionImpl$LogManagersForProject.disposeManager(ServerConnectionImpl.java:403)
	at com.intellij.remoteServer.impl.runtime.ServerConnectionImpl.lambda$disposeAllLogs$4(ServerConnectionImpl.java:303)
	at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707)
	at com.intellij.remoteServer.impl.runtime.ServerConnectionImpl.disposeAllLogs(ServerConnectionImpl.java:303)
	at com.intellij.remoteServer.impl.runtime.ServerConnectionImpl.disposeAllLogs(ServerConnectionImpl.java:299)
	at com.intellij.remoteServer.impl.runtime.deployment.DeploymentImpl.disposeAllLogs(DeploymentImpl.java:71)
	at com.intellij.docker.runtimes.DockerApplicationRuntime.lambda$deleteContainer$0(DockerApplicationRuntime.java:206)
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:705)
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:687)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at com.intellij.docker.runtimes.DockerApplicationRuntime.lambda$makeAgentPromise$1(DockerApplicationRuntime.java:232)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:226)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:26)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2$1.run(BoundedTaskExecutor.java:199)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:229)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:193)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
IntelliJ: 2018.2.4 
Grep Console: 8.4.162.000.1
Docker Integration: 182.4323.18

**Comment by krasa** [comment]
Thanks for the report!
