### ISSUE TITLE
"Wrong filter null" exception after upgrading plugin to latest version

### ISSUE THREAD

**Issue by borice** [krasa/GrepConsole#133]
IntelliJ IDEA prompted me to upgrade my "Grep Console" plugin, to which I consented. After the restart, an "IDE Fatal Errors" window informed me that "Grep Console" threw an exception:

```
java.lang.Throwable: Wrong filter null
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:134)
	at krasa.grepconsole.plugin.ServiceManager.checkConsistency(ServiceManager.java:286)
	at krasa.grepconsole.plugin.ServiceManager.registerConsole(ServiceManager.java:259)
	at krasa.grepconsole.integration.GrepConsoleActionsPostProcessor.postProcess(GrepConsoleActionsPostProcessor.java:29)
	at com.intellij.execution.impl.ConsoleViewImpl.createConsoleActions(ConsoleViewImpl.java:1481)
	at com.intellij.build.BuildView.createConsoleActions(BuildView.java:282)
	at com.intellij.build.AbstractViewManager.configureToolbar(AbstractViewManager.java:122)
	at com.intellij.build.MultipleBuildsView.lambda$onEvent$2(MultipleBuildsView.java:191)
	at com.intellij.build.MultipleBuildsView.lambda$onEvent$3(MultipleBuildsView.java:297)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:668)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
Not sure what's going on, but thought I should post about this error here.

**Comment by krasa** [comment]
Should be already fixed in the newest version 8.6.162.000.4, try to update.
