### ISSUE TITLE
java.lang.NoSuchFieldException: myInputMessageFilter

### ISSUE THREAD

**Issue by msidnin** [krasa/GrepConsole#136]
I constantly get an exception from Grep Console. Usually it happens when application starts. Sometimes when I close a console.

```
java.lang.NoSuchFieldException: myInputMessageFilter
	at java.lang.Class.getDeclaredField(Class.java:2070)
	at krasa.grepconsole.plugin.ReflectionUtils.getPropertyField(ReflectionUtils.java:19)
	at krasa.grepconsole.plugin.ReflectionUtils.getPropertyField(ReflectionUtils.java:24)
	at krasa.grepconsole.plugin.ReflectionUtils.getPropertyField(ReflectionUtils.java:24)
	at krasa.grepconsole.plugin.ReflectionUtils.getPropertyField(ReflectionUtils.java:24)
	at krasa.grepconsole.plugin.ReflectionUtils.getPropertyField(ReflectionUtils.java:24)
	at krasa.grepconsole.plugin.ReflectionUtils.getPropertyField(ReflectionUtils.java:24)
	at krasa.grepconsole.plugin.ReflectionUtils.getField(ReflectionUtils.java:39)
	at krasa.grepconsole.plugin.ReflectionUtils.getPropertyValue(ReflectionUtils.java:83)
	at krasa.grepconsole.plugin.ServiceManager.checkConsistency(ServiceManager.java:288)
	at krasa.grepconsole.plugin.ServiceManager.registerConsole(ServiceManager.java:262)
	at krasa.grepconsole.plugin.ServiceManager.createHighlightFilter(ServiceManager.java:222)
	at krasa.grepconsole.integration.GrepConsoleFilterProvider.getDefaultFilters(GrepConsoleFilterProvider.java:26)
	at com.intellij.execution.impl.ConsoleViewImpl.a(ConsoleViewImpl.java:292)
	at com.intellij.execution.impl.ConsoleViewImpl.<init>(ConsoleViewImpl.java:231)
	at com.intellij.execution.impl.ConsoleViewImpl.<init>(ConsoleViewImpl.java:208)
	at com.intellij.execution.filters.TextConsoleBuilderImpl.createConsole(TextConsoleBuilderImpl.java:57)
	at com.intellij.execution.filters.TextConsoleBuilderImpl.getConsole(TextConsoleBuilderImpl.java:48)
	at com.intellij.openapi.vcs.impl.ProjectLevelVcsManagerImpl.a(ProjectLevelVcsManagerImpl.java:427)
	at com.intellij.openapi.vcs.impl.ProjectLevelVcsManagerImpl.b(ProjectLevelVcsManagerImpl.java:415)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.k(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by krasa** [comment]
IDE, version?

**Comment by krasa** [comment]
Fixed, older paid IDEs obfuscated field names, so it did not work. Sorry. :(

**Comment by msidnin** [comment]
My version is 2017.3.3
Thank you!
