### ISSUE TITLE
Opening recent project leads to crash

### ISSUE THREAD

**Issue by s3r6** [krasa/GrepConsole#149]
**Describe the bug**
Grep console sometimes crashes on opening recent project since 2019.2, also all tool windows hide.

**To Reproduce**
Steps to reproduce the behavior: Go to File - Open recent, select some project

**Expected behavior**
Project opens as usual and all tool windows are available.

**Screenshots**
Project opens without Project tool window opened in my Current layout and no others displayed

**Environment :**
IntelliJ IDEA 2019.2 (Community Edition)
Build #IC-192.5728.98, built on July 23, 2019
Runtime version: 11.0.3+12-b304.10 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-55-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1964M
Cores: 4
Registry: enable.activity.preloading=false, git.explicit.commit.renames.prohibit.multiple.calls=false, suppress.focus.stealing=false
Non-Bundled Plugins: GrepConsole, IDETalk, Identifier Highlighter Reloaded, String Manipulation, com.intellij.stats.completion, com.ppolivka.gitlabprojects, com.jetbrains.upsource, krasa.IdeaIconPack, com.developerphil.adbidea, BashSupport, Docker, org.roana0229.android-xml-sorter, ru.limydesign.plugins.yandex.translate, uk.me.jeffsutton.restconsole, wu.seal.tool.jsontokotlin, zielu.gittoolbox

**Additional context**
Stacktrace in Intellij bug report window
```
java.lang.IllegalArgumentException: window with id="Run" is already registered
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.registerToolWindow(ToolWindowManagerImpl.java:1100)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.registerToolWindow(ToolWindowManagerImpl.java:1080)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.registerToolWindow(ToolWindowManagerImpl.java:1069)
	at com.intellij.execution.ui.RunContentManagerImpl.registerToolWindow(RunContentManagerImpl.java:113)
	at com.intellij.execution.ui.RunContentManagerImpl.init(RunContentManagerImpl.java:73)
	at com.intellij.execution.ui.RunContentManagerImpl.lambda$new$0(RunContentManagerImpl.java:62)
	at com.intellij.ui.AppUIUtil.invokeOnEdt(AppUIUtil.java:190)
	at com.intellij.execution.ui.RunContentManagerImpl.<init>(RunContentManagerImpl.java:62)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:88)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:66)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:48)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.createAndInitialize(ServiceManagerImpl.java:243)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:227)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:246)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:213)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:75)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:49)
	at com.intellij.execution.ui.RunContentManager.getInstance(RunContentManager.java:31)
	at com.intellij.execution.impl.ExecutionManagerImpl.getContentManager(ExecutionManagerImpl.java:234)
	at com.intellij.execution.ExecutionHelper.lambda$findRunningConsole$4(ExecutionHelper.java:221)
	at com.intellij.execution.ExecutionHelper.findRunningConsole(ExecutionHelper.java:243)
	at krasa.grepconsole.grep.OpenGrepConsoleAction.getRunContentDescriptor(OpenGrepConsoleAction.java:279)
	at krasa.grepconsole.grep.PinnedGrepsReopener$1.lambda$run$0(PinnedGrepsReopener.java:50)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:312)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:433)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:873)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:461)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:460)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by krasa** [comment]
What kind of project? Those which I tried did not call it at all at reopening.

**Comment by krasa** [comment]
well, anyway, try this: https://github.com/krasa/GrepConsole/releases/tag/9.6.162.000.0

**Comment by s3r6** [comment]
Android Gradle project. Thanks for response, I will update.
