### ISSUE TITLE
Couldn't open Grep Console Settings window

### ISSUE THREAD

**Issue by kfirfer** [krasa/GrepConsole#168]
Grep Console version:  9.10.193
Intellij ultimate version: 2019.3.4

Without internet access of the machine (at all), installed intellij + plugin(from disk zip) offline

After that, Couldn't click on the button "Open Grep Console Settings"  (The settings of the grep console) Nothing is showing or popup

**Comment by krasa** [comment]
screenshot?

**Comment by kfirfer** [comment]
![20200422_152309](https://user-images.githubusercontent.com/7741545/79981391-46304a80-84ad-11ea-80c2-a6ef4a52520a.jpg)

**Comment by krasa** [comment]
Strange, almost like a corrupted installation, is something in the log? I would try to uninstall, restart, install again.

**Comment by kfirfer** [comment]
yes it is, I tried twice, its happens me also on windows 7 and windows 10

**Comment by kfirfer** [comment]
but please install completly from scretch without internet access at all

**Comment by krasa** [comment]
I just did that, works fine.

**Comment by kfirfer** [comment]
I took the exception from the plugin, it seems he find the ImageIcon(perhaps from internet?)  and could not load it

This is the full stacktrace:


```
java.lang.NullPointerException
	at java.desktop/javax.swing.ImageIcon.<init>(ImageIcon.java:217)
	at krasa.grepconsole.gui.ProfileDetailForm.$$$setupUI$$$(ProfileDetailForm.java)
	at krasa.grepconsole.gui.ProfileDetailForm.<init>(ProfileDetailForm.java:96)
	at krasa.grepconsole.gui.CompositeSettingsForm.<init>(CompositeSettingsForm.java:60)
	at krasa.grepconsole.plugin.MyConfigurable.prepareForm(MyConfigurable.java:160)
	at krasa.grepconsole.action.OpenConsoleSettingsAction.actionPerformed(OpenConsoleSettingsAction.java:33)
	at krasa.grepconsole.action.OpenConsoleSettingsAction.actionPerformed(OpenConsoleSettingsAction.java:27)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:298)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:315)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:289)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:194)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:157)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:447)
	at java.desktop/java.awt.Component.processEvent(Component.java:6416)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:908)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:846)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:778)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:424)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by krasa** [comment]
Could you post: Help | About | click on copy button?

**Comment by kfirfer** [comment]
```
IntelliJ IDEA 2019.3.4 (Ultimate Edition)

Build #IU-193.6911.18, built on March 17, 2020

Licensed to XXXXXXX / XXXXXXX

Subscription is active until June 3, 2020

Runtime version: 11.0.6+8-b520.43 amd64

VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Windows 10 10.0

GC: ParNew, ConcurrentMarkSweep

Memory: 1998M

Cores: 4

Registry:

Non-Bundled Plugins: BashSupport, DBN, GrepConsole, GsonFormat, Lombook Plugin, com.atlassian.bitbucket.references, com.dmarcotte.handlebars, com.github.setial, org.jetbrains.plugins.go-template, com.intellij.kubernetes, ideanginx9, mobi.hsz.idea.gitignore, name.kropp.intellij.makefile, net.seesharpsoft.intellij.plugins.csv, org.intellij.plugins.hcl, org.zalando.intellij.swagger, ru.adelf.idea.dotenv
```

**Comment by krasa** [comment]
This seems really strange, your JRE is ok, that plugin version has 10+k downloads, everything seems fine, so I don't see what could it be other than a corrrupted download, or some antivirus issue. You could check that icons are there, `C:\Users\XXX\.IntelliJIdea2019.3\config\plugins\GrepConsole\lib\GrepConsole.jar 
` 
Perhaps JetBrains support would know something more. 

![image](https://user-images.githubusercontent.com/1160875/80116041-c75b1080-8585-11ea-940f-c9948bd3ca10.png)

**Comment by krasa** [comment]
If you had IJ 2020.1, then it would be clear, they screwed something... https://youtrack.jetbrains.com/issue/IDEA-237519

**Comment by kfirfer** [comment]
yes the icons are there
![15876561267725457529695611941617](https://user-images.githubusercontent.com/7741545/80118568-4144c700-8591-11ea-93dd-9adb431028e2.jpg)

**Comment by krasa** [comment]
But they have a different extension. They should be png or gif, never jpg.

**Comment by kfirfer** [comment]
oh , thats really wired, how comes ?

**Comment by krasa** [comment]
No idea, but you can see their date, something changed them yesterday.

**Comment by kfirfer** [comment]
It is not relating to the plugin suppose, perhpas some antivirus or third party vendor in the middle
So I closing the ticket, thanks very much for the support !

**Comment by krasa** [comment]
Well, let me know if you find out what did it. Just curious. :-)
