### ISSUE TITLE
"IllegalArgumentException: Do not request resource from classloader using path with leading slash (path=/krasa/grepconsole/icons/donate.png)"

### ISSUE THREAD

**Issue by ewirch** [krasa/GrepConsole#186]
**Describe the bug**
An exception was recorded by IntelliJ error reporting.

```
java.lang.IllegalArgumentException: Do not request resource from classloader using path with leading slash (path=/krasa/grepconsole/icons/donate.png)
	at com.intellij.util.lang.UrlClassLoader.findResource(UrlClassLoader.java:284)
	at java.base/java.lang.ClassLoader.getResource(ClassLoader.java:1410)
	at com.intellij.ide.plugins.cl.PluginClassLoader.findResource(PluginClassLoader.java:383)
	at java.base/java.lang.ClassLoader.getResource(ClassLoader.java:1410)
	at java.base/java.lang.Class.getResource(Class.java:2898)
	at krasa.grepconsole.gui.ProfileDetailForm.$$$setupUI$$$(ProfileDetailForm.java)
	at krasa.grepconsole.gui.ProfileDetailForm.<init>(ProfileDetailForm.java:96)
	at krasa.grepconsole.gui.CompositeSettingsForm.<init>(CompositeSettingsForm.java:60)
	at krasa.grepconsole.gui.CompositeSettingsForm.<init>(CompositeSettingsForm.java:50)
	at krasa.grepconsole.plugin.MyConfigurable.createComponent(MyConfigurable.java:78)
	at krasa.grepconsole.plugin.runConfiguration.GrepSettingsEditor.createEditor(GrepSettingsEditor.java:50)
	at com.intellij.openapi.options.SettingsEditor.getComponent(SettingsEditor.java:98)
	at com.intellij.execution.impl.ConfigurationSettingsEditor$ConfigToSettingsWrapper.createEditor(ConfigurationSettingsEditor.java:318)
	at com.intellij.openapi.options.SettingsEditor.getComponent(SettingsEditor.java:98)
	at com.intellij.openapi.options.GroupSettingsBuilder.doCreateComponent(GroupSettingsBuilder.java:65)
	at com.intellij.openapi.options.GroupSettingsBuilder.createCompoundEditor(GroupSettingsBuilder.java:51)
	at com.intellij.openapi.options.CompositeSettingsEditor.createEditor(CompositeSettingsEditor.java:100)
	at com.intellij.openapi.options.SettingsEditor.getComponent(SettingsEditor.java:98)
	at com.intellij.execution.impl.ConfigurationSettingsEditorWrapper.createEditor(ConfigurationSettingsEditorWrapper.java:121)
	at com.intellij.openapi.options.SettingsEditor.getComponent(SettingsEditor.java:98)
	at com.intellij.openapi.options.SettingsEditor.lambda$resetFrom$0(SettingsEditor.java:75)
	at com.intellij.openapi.options.SettingsEditor.bulkUpdate(SettingsEditor.java:84)
	at com.intellij.openapi.options.SettingsEditor.resetFrom(SettingsEditor.java:74)
	at com.intellij.openapi.options.SettingsEditorConfigurable.reset(SettingsEditorConfigurable.java:39)
	at com.intellij.execution.impl.SingleConfigurationConfigurable.reset(SingleConfigurationConfigurable.java:156)
	at com.intellij.execution.impl.SingleConfigurationConfigurable.editSettings(SingleConfigurationConfigurable.java:123)
	at com.intellij.execution.impl.RunDialog.editConfiguration(RunDialog.java:106)
	at com.intellij.execution.actions.ChooseRunConfigurationPopup.editConfiguration(ChooseRunConfigurationPopup.java:197)
	at com.intellij.execution.actions.ChooseRunConfigurationPopup$ConfigurationActionsStep$3.perform(ChooseRunConfigurationPopup.java:614)
	at com.intellij.execution.actions.ChooseRunConfigurationPopup$ConfigurationActionsStep.lambda$onChosen$0(ChooseRunConfigurationPopup.java:642)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95)
	at com.intellij.ui.popup.AbstractPopup.lambda$dispose$18(AbstractPopup.java:1465)
	at com.intellij.util.ui.EdtInvocationManager.invokeLaterIfNeeded(EdtInvocationManager.java:101)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:187)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:139)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:173)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.doWhenFocusSettlesDown(IdeFocusManagerImpl.java:36)
	at com.intellij.ui.popup.AbstractPopup.dispose(AbstractPopup.java:1461)
	at com.intellij.ui.popup.WizardPopup.dispose(WizardPopup.java:160)
	at com.intellij.ui.popup.list.ListPopupImpl.dispose(ListPopupImpl.java:329)
	at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:138)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:168)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:150)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:138)
	at com.intellij.ui.popup.WizardPopup.disposeAllParents(WizardPopup.java:263)
	at com.intellij.ui.popup.WizardPopup.disposeAllParents(WizardPopup.java:265)
	at com.intellij.ui.popup.list.ListPopupImpl.handleNextStep(ListPopupImpl.java:446)
	at com.intellij.ui.popup.list.ListPopupImpl._handleSelect(ListPopupImpl.java:418)
	at com.intellij.ui.popup.list.ListPopupImpl.handleSelect(ListPopupImpl.java:359)
	at com.intellij.ui.popup.list.ListPopupImpl$1.actionPerformed(ListPopupImpl.java:272)
	at com.intellij.ui.popup.WizardPopup.proceedKeyEvent(WizardPopup.java:375)
	at com.intellij.ui.popup.WizardPopup.dispatch(WizardPopup.java:351)
	at com.intellij.ui.popup.PopupDispatcher.dispatchKeyEvent(PopupDispatcher.java:112)
	at com.intellij.ui.popup.PopupDispatcher.dispatch(PopupDispatcher.java:148)
	at com.intellij.ide.IdePopupManager.dispatch(IdePopupManager.java:93)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:448)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:783)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:782)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:501)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**To Reproduce**
Not sure. I think I opened the run configuration window.

**Expected behavior**
No exception is being thrown.

**Environment :**
IntelliJ IDEA 2021.1 EAP (Ultimate Edition)
Build #IU-211.5538.20, built on February 4, 2021
IntelliJ IDEA EAP User
Expiration date: March 6, 2021
Runtime version: 15.0.1+9-18 amd64
VM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation
Linux 5.10.7-3-manjaro
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Registry: diff.patience.alg=true, debugger.valueTooltipAutoShow=false, ide.usages.page.size=200, show.diff.as.editor.tab=true, external.system.auto.import.disabled=true, unknown.sdk=false
Non-Bundled Plugins: com.ivanovych666.intellij.plugin.jsonsorter (1.0.0-beta.3.4), org.intellij.plugins.hcl (0.7.10), name.kropp.intellij.makefile (211.5538.10), org.nik.presentation-assistant (1.0.9), org.toml.lang (0.2.140.3644-203), GrepConsole (11.4.202.000.0), com.jetbrains.packagesearch.intellij-plugin (1.0.1428-eap), org.asciidoctor.intellij.asciidoc (0.32.15), Pythonid (211.5538.20), org.rust.lang (0.3.140.3644-203)
Kotlin: 211-1.4.21-release-IJ5538.2
Current Desktop: XFCE

**Comment by krasa** [comment]
Thanks! You can update.
