### ISSUE TITLE
Problem in IntelliJ2021.1 EAP 2

### ISSUE THREAD

**Issue by renoth** [krasa/GrepConsole#187]
**Describe the bug**
Stacktrace in idea.log when starting IntelliJ, prevents other plugins from working.

**To Reproduce**
1. Start IDE with Plugin activated

> 2021-02-10 13:15:41,629 [ 257246]  ERROR - pplication.impl.LaterInvocator - Do not request resource from classloader using path with leading slash (path=/krasa/grepconsole/icons/donate.png) 
java.lang.IllegalArgumentException: Do not request resource from classloader using path with leading slash (path=/krasa/grepconsole/icons/donate.png)
	at com.intellij.util.lang.UrlClassLoader.findResource(UrlClassLoader.java:284)
	at java.base/java.lang.ClassLoader.getResource(ClassLoader.java:1401)
	at com.intellij.ide.plugins.cl.PluginClassLoader.findResource(PluginClassLoader.java:383)
	at java.base/java.lang.ClassLoader.getResource(ClassLoader.java:1401)
	at java.base/java.lang.Class.getResource(Class.java:2740)
	at krasa.grepconsole.gui.ProfileDetailForm.$$$setupUI$$$(ProfileDetailForm.java)
	at krasa.grepconsole.gui.ProfileDetailForm.<init>(ProfileDetailForm.java:96)
	at krasa.grepconsole.gui.CompositeSettingsForm.<init>(CompositeSettingsForm.java:60)
	at krasa.grepconsole.gui.CompositeSettingsForm.<init>(CompositeSettingsForm.java:50)
	at krasa.grepconsole.plugin.MyConfigurable.createComponent(MyConfigurable.java:78)
	at krasa.grepconsole.plugin.runConfiguration.GrepSettingsEditor.createEditor(GrepSettingsEditor.java:50)
	at com.intellij.openapi.options.SettingsEditor.getComponent(SettingsEditor.java:98)
	at com.intellij.execution.ui.SettingsEditorFragment.createWrapper(SettingsEditorFragment.java:80)
	at com.intellij.execution.configuration.RunConfigurationExtensionsManager.createFragments(RunConfigurationExtensionsManager.kt:122)

**Comment by krasa** [comment]
updat the plugin

**Comment by renoth** [comment]
update is not possible it says "download or installation not possible"

**Comment by krasa** [comment]
what exactly gives the error? screenshot?
That update has 18 780 downloads, and works for me.

**Comment by renoth** [comment]
![image](https://user-images.githubusercontent.com/4069007/107521686-250f2680-6bb3-11eb-9156-057d8b5168f2.png)

The idea log does not give any information whatsoever, i will try to uninstall all other plugins and test again.

**Comment by renoth** [comment]
i used a completely blank config directory for IntelliJ but the error persists. I cannot install the plugin in the latest version in IntelliJ 2021.1 EAP 2

**Comment by krasa** [comment]
And by EAP 2 you mean: 
IntelliJ IDEA 2021.1 EAP (Community Edition)
Build #IC-211.5538.20, built on February 4, 2021

There was one case when some firewall altered the downloaded zip/jar so that it could not be installed.
You could try to download it manually https://plugins.jetbrains.com/plugin/7125-grep-console/versions/stable/109958
and install it (e.g. by dragging into the editor) and if that fails upload that file here.

**Comment by krasa** [comment]
nevermind, look here: https://youtrack.jetbrains.com/issue/IDEA-261296

**Comment by renoth** [comment]
Yes Version 211.5538.20. I tried to manually install the plugin from disk and got the following result:
![image](https://user-images.githubusercontent.com/4069007/107524553-31e14980-6bb6-11eb-9837-4dd431832b3f.png)

The File is 

[GrepConsole.zip](https://github.com/krasa/GrepConsole/files/5958853/GrepConsole.zip)

**Comment by renoth** [comment]
i also emptied the appdata temp folder completely before retrying.

**Comment by renoth** [comment]
ok thanks for the info with youtrack, issue can be closed then :) Thanks for your help and the great plugin :)
