### ISSUE TITLE
error

### ISSUE THREAD

**Issue by zwxx960** [krasa/GrepConsole#191]
java.lang.RuntimeException: IJ API was probably changed, update the plugin or report it

at krasa.grepconsole.utils.Rehighlighter.highlightAll(Rehighlighter.java:52)

at krasa.grepconsole.utils.Rehighlighter.reset(Rehighlighter.java:31)

at krasa.grepconsole.utils.Rehighlighter.resetHighlights(Rehighlighter.java:19)

at krasa.grepconsole.plugin.ServiceManager.rehighlight(ServiceManager.java:350)

at krasa.grepconsole.gui.ProfileDetailForm$3.actionPerformed(ProfileDetailForm.java:124)

at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)

at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)

at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)

at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)

at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)

at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)

at java.desktop/java.awt.Component.processMouseEvent(Component.java:6635)

at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)

at java.desktop/java.awt.Component.processEvent(Component.java:6400)

at java.desktop/java.awt.Container.processEvent(Container.java:2263)

at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)

at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)

at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)

at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)

at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)

at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)

at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)

at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)

at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)

at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)

at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)

at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)

at java.base/java.security.AccessController.doPrivileged(Native Method)

at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)

at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)

at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)

at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)

at java.base/java.security.AccessController.doPrivileged(Native Method)

at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)

at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)

at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)

at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:911)

at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:840)

at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)

at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)

at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)

at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)

at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:507)

at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)

at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)

at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)

at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)

at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)

at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)

at java.base/java.security.AccessController.doPrivileged(Native Method)

at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)

at java.desktop/java.awt.Dialog.show(Dialog.java:1070)

at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:694)

at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:435)

at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1715)

at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1674)

at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:90)

at com.intellij.ide.actions.ShowSettingsAction.perform(ShowSettingsAction.java:55)

at com.intellij.ide.actions.ShowSettingsAction.actionPerformed(ShowSettingsAction.java:42)

at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:281)

at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:310)

at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:286)

at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:77)

at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:299)

at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)

at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:110)

at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95)

at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:110)

at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:514)

at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:544)

at java.desktop/java.awt.Component.processMouseEvent(Component.java:6635)

at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)

at java.desktop/java.awt.Component.processEvent(Component.java:6400)

at java.desktop/java.awt.Container.processEvent(Container.java:2263)

at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)

at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)

at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)

at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)

at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)

at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)

at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)

at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)

at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)

at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)

at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)

at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)

at java.base/java.security.AccessController.doPrivileged(Native Method)

at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)

at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)

at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)

at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)

at java.base/java.security.AccessController.doPrivileged(Native Method)

at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)

at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)

at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)

at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:911)

at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:840)

at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)

at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)

at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)

at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)

at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:507)

at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)

at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)

at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)

at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)

at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)

at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

Caused by: java.lang.NoSuchFieldException: myFilters

at java.base/java.lang.Class.getDeclaredField(Class.java:2411)

at krasa.grepconsole.plugin.ReflectionUtils.getPropertyField(ReflectionUtils.java:19)

at krasa.grepconsole.plugin.ReflectionUtils.getPropertyField(ReflectionUtils.java:24)

at krasa.grepconsole.plugin.ReflectionUtils.getPropertyField(ReflectionUtils.java:24)

at krasa.grepconsole.plugin.ReflectionUtils.getPropertyField(ReflectionUtils.java:24)

at krasa.grepconsole.plugin.ReflectionUtils.getPropertyField(ReflectionUtils.java:24)

at krasa.grepconsole.plugin.ReflectionUtils.getPropertyField(ReflectionUtils.java:24)

at krasa.grepconsole.plugin.ReflectionUtils.getField(ReflectionUtils.java:39)

at krasa.grepconsole.plugin.ReflectionUtils.getPropertyValue(ReflectionUtils.java:83)

at krasa.grepconsole.utils.Rehighlighter.highlightAll(Rehighlighter.java:44)

... 107 more

**Comment by zwxx960** [comment]
version 10.1.201.4515.0

**Comment by krasa** [comment]
IDE version?

**Comment by krasa** [comment]
> version 10.1.201.4515.0

very old.
https://plugins.jetbrains.com/plugin/7125-grep-console/versions/stable/109958
