### ISSUE TITLE
NoPlayerException when a item with sound is triggered

### ISSUE THREAD

**Issue by isandrade** [krasa/GrepConsole#196]
**Describe the bug**
NoPlayerException is throw when a item with sound is triggered

**To Reproduce**
1. Set sound for an item:
![image](https://user-images.githubusercontent.com/13832752/119583006-13394400-bd9c-11eb-8a59-8f363f5eb456.png)
2. Trigger this item on console.
3. Intellij shows error notification, when i open i see this exception: javax.media.NoPlayerException: Cannot find a Player for :file:/path/to/Sound/complete.oga

**Environment :**
IntelliJ IDEA 2021.1.1 (Ultimate Edition)
Build #IU-211.7142.45, built on April 30, 2021
Licensed to Igor Andrade
Subscription is active until November 25, 2021.
Runtime version: 11.0.10+9-b1341.41 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-72-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1896M
Cores: 8
Non-Bundled Plugins: Key Promoter X (2021.1.1), com.tobszarny.activetabhighlighter.plugin.id (1.4.0), com.wakatime.intellij.plugin (13.0.2), manjaro.mpb (1.6), GrepConsole (11.9.211.6086.0), com.bruce.intellijpluin.stackoverflow (1.1), com.dubreuia (2.2.0), org.sonarlint.idea (4.16.0.31683), intellij.prettierJS (211.7142.13), com.codota.csp.intellij (4.2.5), Karma (211.6693.111), org.jetbrains.kotlin (211-1.5.0-release-759-IJ6693.72), Pythonid (211.7142.45), net.ashald.envfile (3.2.1), ru.adelf.idea.dotenv (2021.1)
Kotlin: 211-1.5.0-release-759-IJ6693.72
Current Desktop: X-Cinnamon

**Expected behavior**
Sound to be played

**Full stacktrace**
```Playing of sound failed. Sound file path=/home/igor/Dev/Programs/IDEs/Settings/Sound/complete.oga, exists:true.
javax.media.NoPlayerException: Cannot find a Player for :file:/home/igor/Dev/Programs/IDEs/Settings/Sound/complete.oga
	at javax.media.Manager.createPlayerForContent(Manager.java:1412)
	at javax.media.Manager.createPlayer(Manager.java:417)
	at javax.media.Manager.createPlayer(Manager.java:332)
	at krasa.grepconsole.model.PlayerUtil.play(PlayerUtil.java:10)
	at krasa.grepconsole.model.Sound.play(Sound.java:30)
	at krasa.grepconsole.filter.support.FilterState.executeAction(FilterState.java:138)
	at krasa.grepconsole.filter.support.ThreadUnsafeGrepProcessor.process(ThreadUnsafeGrepProcessor.java:62)
	at krasa.grepconsole.filter.AbstractMatchingFilter.filter(AbstractMatchingFilter.java:45)
	at krasa.grepconsole.filter.HighlightingFilter.applyFilter(HighlightingFilter.java:37)
	at com.intellij.execution.filters.CompositeFilter.applyFilter(CompositeFilter.java:79)
	at com.intellij.execution.impl.AsyncFilterRunner$HighlighterJob.analyzeLine(AsyncFilterRunner.java:231)
	at com.intellij.execution.impl.AsyncFilterRunner$HighlighterJob.analyzeNextLine(AsyncFilterRunner.java:220)
	at com.intellij.execution.impl.AsyncFilterRunner.runTasks(AsyncFilterRunner.java:148)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:521)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:468)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:79)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:157)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:119)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:116)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:79)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:408)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)```

**Comment by krasa** [comment]
ogg does not seem to be supported.
wav or mp3 should work
