### ISSUE TITLE
report a error on IDEA 2021.2.1 Ultimate Edition

### ISSUE THREAD

**Issue by minshiwu** [krasa/GrepConsole#200]
IDEA 2021.2.1 Ultimate Edition

```text
Please report this

java.lang.ClassCastException: class [Lcom.intellij.execution.filters.CompositeInputFilter$InputFilterWrapper; cannot be cast to class java.util.List ([Lcom.intellij.execution.filters.CompositeInputFilter$InputFilterWrapper; is in unnamed module of loader com.intellij.util.lang.PathClassLoader @6df97b55; java.util.List is in module java.base of loader 'bootstrap')
	at krasa.grepconsole.plugin.ServiceManager.getInputFilter(ServiceManager.java:284)
	at krasa.grepconsole.plugin.ServiceManager.registerConsole(ServiceManager.java:254)
	at krasa.grepconsole.integration.MyConsoleActionsPostProcessor.postProcess(MyConsoleActionsPostProcessor.java:32)
	at com.intellij.execution.impl.ConsoleViewImpl.createConsoleActions(ConsoleViewImpl.java:1370)
	at com.intellij.database.console.JdbcConsoleUtil.addLeftToolbarConsoleActions(JdbcConsoleUtil.java:11)
	at com.intellij.database.console.session.DatabaseLogView.buildConsoleUi(DatabaseLogView.java:132)
	at com.intellij.database.run.session.BaseLogView.ensureContentInitialized(BaseLogView.java:204)
	at com.intellij.database.console.session.DatabaseLogView.<init>(DatabaseLogView.java:62)
	at com.intellij.database.console.session.DatabaseSessionLogView.<init>(DatabaseSessionLogView.java:17)
	at com.intellij.database.console.session.DatabaseSessionViewServiceImpl$getView$1.apply(DatabaseSessionViewServiceImpl.kt:30)
	at com.intellij.database.console.session.DatabaseSessionViewServiceImpl$getView$1.apply(DatabaseSessionViewServiceImpl.kt:21)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at com.intellij.database.console.session.DatabaseSessionViewServiceImpl.getView(DatabaseSessionViewServiceImpl.kt:26)
	at com.intellij.database.console.session.DatabaseSessionViewServiceImpl.initView(DatabaseSessionViewServiceImpl.kt:37)
	at com.intellij.database.console.session.MessageBusSession$attach$1.run(MessageBusSession.kt:160)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:887)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:442)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:494)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by krasa** [comment]
plugin version?

**Comment by minshiwu** [comment]
plugin version: 10.0.201.4515.0

**Comment by minshiwu** [comment]
upgrade to 11.10.211.6086.0 OK。
