### ISSUE TITLE
JetBrains Rider cannot use this plugin in Run window

### ISSUE THREAD

**Issue by Honsal** [krasa/GrepConsole#214]
**Describe the bug**
No grep console toolbar appears, 'Grep' command is not working, no lines highlighted according to color/regex settings.

**To Reproduce**
1. Install latest JetBrains Rider from JetBrains toolbox.
2. Install some plugins like Material Theme UI
3. Install Grep Console plugin
4. Launch ASP.NET 6 project without debugging.
5. Goto 'Run' window
6. Seeing nothing highlighted
7. Try to use 'Grep' command using double shift
8. An error occured

**Expected behavior**
Logs should be highlighted/colored, 'Grep' command should be working, Grep Console toolbar must be appeared on 'Run' window.

**Screenshots**
|![image](https://user-images.githubusercontent.com/13115858/155484205-85a51004-62eb-4195-9c60-b4bce64572ce.png)|
|:--:|
|*Grep Console settings*|

|![image](https://user-images.githubusercontent.com/13115858/155484627-9dbac6f0-9657-49d7-a528-79b5031f401b.png)|
|:--:|
|*Run window. TRACE and INFO must be colored.*|

|![image](https://user-images.githubusercontent.com/13115858/155484865-ef4bc155-fd8d-4e5d-a14a-d39616daf961.png)|
|:--:|
|*Using grep command on Run window*|
|![image](https://user-images.githubusercontent.com/13115858/155485011-bb6027d9-413f-47f3-b602-18e2be6c2979.png)|
|*Result. Entire error message is placed below **Additional context** section.*|

|![image](https://user-images.githubusercontent.com/13115858/155485310-7b24709c-599d-4c91-92ad-84e9a0d5cbd1.png)|
|:--:|
|*In **Build** window, it works well.*|

**Environment :**
```
JetBrains Rider 2021.3.3
Build #RD-213.6775.4, built on January 26, 2022
Licensed to **DELETED**
Subscription is active until March 4, 2022.
Runtime version: 11.0.13+7-b1751.25 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
.NET Framework 4.0.30319.42000
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 48
Registry:
    ide.balloon.shadow.size=0
    ide.new.project.model.index.case.sensitivity=true
    rdclient.asyncActions=false
    indexing.enable.entity.provider.based.indexing=false

Non-Bundled Plugins:
    testlinker2-rider (2021.3.3)
    org.toml.lang (213.5744.224)
    org.nik.presentation-assistant (1.0.9)
    org.intellij.RegexpTester (1.0.8)
    nl.bryanderidder.regexrenamefiles (1.1.7)
    internalsvisibleto-rider (2021.3.0)
    fluentvalidation-rider (2021.3.0)
    fluentassertions-rider (2021.3.2)
    com.settler.rider.specflow (1.10.2)
    com.intellij.resharper.StructuredLogging (2021.3.3.184)
    com.intellij.resharper.HeapAllocationsViewer (2021.3.0)
    com.intellij.resharper.ConfigurationSense (2021.3.0.131)
    com.intellij.plugins.macoskeymap (213.5744.3)
    com.github.copilot (1.1.12.524)
    cognitivecomplexity-rider (2021.3.0)
    XmlDocInspections (2.15.0.828)
    com.jetbrains.rider.android (213.6775.4)
    com.intellij.plugin.adernov.powershell (2.0.9)
    Roflcopter (1.14.0.596)
    com.intellij.resharper.azure (3.50.0.1314-2021.3)
    com.chrisrm.idea.MaterialThemeUI (6.13.0)
    GrepConsole (12.5.211.6693.2)
    zielu.gittoolbox (212.8.5)
    mobi.hsz.idea.gitignore (4.3.0)
    com.mallowigi (54.1.0)
    aws.toolkit (1.38-213)
    DBN (3.3.1555.0)
```

**Additional context**

Entire error message when use 'Grep' command on Run Window:

```
java.lang.RuntimeException: console not supported, must be instance of JComponent: com.intellij.terminal.TerminalExecutionConsole@2587b50f
	at krasa.grepconsole.grep.actions.OpenGrepConsoleAction.createGrepConsole(OpenGrepConsoleAction.java:95)
	at krasa.grepconsole.grep.actions.OpenGrepConsoleAction.actionPerformed(OpenGrepConsoleAction.java:83)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:244)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:265)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:244)
	at com.intellij.ide.actions.GotoActionAction.performActionImpl(GotoActionAction.java:111)
	at com.intellij.ide.actions.GotoActionAction.lambda$performAction$2(GotoActionAction.java:84)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:348)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:131)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:187)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)```

**Comment by krasa** [comment]
The error is quite right, the Terminal is not supported. https://github.com/krasa/GrepConsole/issues/145

**Comment by Honsal** [comment]
> The error is quite right, the Terminal is not supported. #145

Thanks for reply. I couldn't make run it on other windows. I hope they support API soon.

Closing this issue.
