### ISSUE TITLE
Exception in Grep Console (10.1.201.4514.0) in IntelliJ Pycharm Professional

### ISSUE THREAD

**Issue by BobHonea** [krasa/GrepConsole#219]
**Describe the bug**
While using Pycharm Professional 2021.3.2 (Professional Edition, Build #PY-213.6777.50 built Jan 27 2022),
an exception is thrown as follows:
Please report this

java.lang.ClassCastException: class [Lcom.intellij.execution.filters.CompositeInputFilter$InputFilterWrapper; cannot be cast to class java.util.List ([Lcom.intellij.execution.filters.CompositeInputFilter$InputFilterWrapper; is in unnamed module of loader com.intellij.util.lang.PathClassLoader @6615435c; java.util.List is in module java.base of loader 'bootstrap')
	at krasa.grepconsole.plugin.ServiceManager.getInputFilter(ServiceManager.java:284)
	at krasa.grepconsole.plugin.ServiceManager.registerConsole(ServiceManager.java:254)
	at krasa.grepconsole.plugin.ServiceManager.createHighlightFilter(ServiceManager.java:213)
	at krasa.grepconsole.integration.MyConsoleFilterProvider.getDefaultFilters(MyConsoleFilterProvider.java:30)
	at com.intellij.execution.impl.ConsoleViewUtil.computeConsoleFilters(ConsoleViewUtil.java:254)
	at com.intellij.execution.impl.ConsoleViewImpl.lambda$updatePredefinedFiltersLater$1(ConsoleViewImpl.java:229)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:521)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1084)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:158)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:115)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:112)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:407)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

**To Reproduce**
1. Start Pycharm Pro which has a project configured
2. Wait until project loading / progress bar completes
3. Select an executable <module name>.py module from within the project as context
4. From within that module in the editor, right click for menu and click 'Debug <module name>...'
5. The error message "IDE error occurred" - 'See details and submit report' is displayed in LR corner of IDE
6. The Debug operation proceeds, and is not hindered.
7. On opening, the ensuing dialog opened showing the (now pasted above) exception log.

**Expected behavior**
I expected the Debug execution to proceed without any surprise dialogs.
Otherwise, no noticeable discernable problems or deviations from expectation occurred.

**Screenshots**
--judged unnecessary

**Environment :**
PyCharm 2021.3.2 (Professional Edition)
Build #PY-213.6777.50, built on January 27, 2022
Licensed to Bob Honea
Subscription is active until April 27, 2022.
Runtime version: 11.0.13+7-b1751.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1008M
Cores: 8
Non-Bundled Plugins:
    GrepConsole (10.1.201.4515.0)

**Additional context**
-no idea what else is germane

**Comment by krasa** [comment]
The problem might be that you are using 2 years old plugin version, try to update.
