### ISSUE TITLE
Connot grep word in IntelliJ IDEA 2023.1

### ISSUE THREAD

**Issue by vaple** [krasa/GrepConsole#262]
**Describe the bug**
When grep word in run console,there is no grep window and idea notify error as
```java
java.lang.IllegalStateException: Console not supported: com.intellij.execution.impl.ConsoleViewImpl[,0,0,1664x1007,layout=java.awt.BorderLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=]
	at krasa.grepconsole.grep.OpenGrepConsoleAction.createGrepConsole(OpenGrepConsoleAction.java:99)
	at krasa.grepconsole.grep.OpenGrepConsoleAction.actionPerformed(OpenGrepConsoleAction.java:79)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:333)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:307)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:356)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:307)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$performAction$5(ActionMenuItem.java:299)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:225)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.performAction(ActionMenuItem.java:292)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$new$0(ActionMenuItem.java:67)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$4(ActionMenuItem.java:114)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:114)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:526)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:558)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6656)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3385)
	at java.desktop/java.awt.Component.processEvent(Component.java:6421)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2804)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:790)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:763)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:761)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:666)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:614)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:569)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:994)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:994)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Environment :**
`IntelliJ IDEA 2023.1 (Ultimate Edition) Build #IU-231.8109.175, built on March 28, 2023`

**Comment by krasa** [comment]
For which Run Configuration?

**Comment by vaple** [comment]
> For which Run Configuration?

all default

**Comment by krasa** [comment]
So Gradle, JUnit... all?  
![image](https://user-images.githubusercontent.com/1160875/229449269-9d3c098f-92c5-4d4a-af6b-2ca142ee1cb4.png)

Works fine for me

**Comment by vaple** [comment]
> So Gradle, JUnit... all? ![image](https://user-images.githubusercontent.com/1160875/229449269-9d3c098f-92c5-4d4a-af6b-2ca142ee1cb4.png)
> 
> Works fine for me

sorry, I thought you were asking about grep console settings

**Comment by krasa** [comment]
cannot reproduce 
![image](https://user-images.githubusercontent.com/1160875/229460792-d0a9662f-97d0-4f6d-9e67-b076c6fa85ca.png)

**Comment by vaple** [comment]
> cannot reproduce ![image](https://user-images.githubusercontent.com/1160875/229460792-d0a9662f-97d0-4f6d-9e67-b076c6fa85ca.png)
problem seems to be that there are no sub console tab here
![image](https://user-images.githubusercontent.com/46566508/230254531-dc918ab4-d9e1-4a18-b70a-cc5be91137e1.png)

**Comment by krasa** [comment]
it looks a little different
![image](https://user-images.githubusercontent.com/1160875/230306110-07412c66-6f9b-4949-bdcc-861e816d1e04.png)
![image](https://user-images.githubusercontent.com/1160875/230306135-2624cf7d-b383-4398-b2e8-3c31f8ce5d03.png)

**Comment by gelldur** [comment]
In Clion 2023.1 they introduced emulation of terminal so maybe related. Turn this off for fix.
![image](https://user-images.githubusercontent.com/175790/233829105-17b6f7eb-1821-490c-8b9c-5e99ed3db846.png)

**Comment by vaple** [comment]
> 

not found this option in 
IntelliJ IDEA 2023.1 (Ultimate Edition)
Build #IU-231.8109.175, built on March 28, 2023
![image](https://user-images.githubusercontent.com/46566508/234153888-0b3abb72-bf07-408b-a22c-4b83768562f9.png)

**Comment by vaple** [comment]
and unrelated to Run Configuration,same error in maven package 
![image](https://user-images.githubusercontent.com/46566508/234154230-f33b94bc-ba3b-435a-b52c-e905539d7d48.png)

**Comment by krasa** [comment]
Please post `Help | About  | Copy`....

```
IntelliJ IDEA 2023.1.1 Preview (Ultimate Edition)
Build #IU-231.8770.17, built on April 14, 2023
Runtime version: 17.0.6+10-b829.9 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 24
Registry:
    performance.watcher.sampling.interval.ms=500
    performance.watcher.unresponsive.interval.ms=500
    terminal.use.conpty.on.windows=false
    performance.watcher.unresponsive.max.attempts.before.log=2

Non-Bundled Plugins:
    FrameSwitcher (4.0.0-223)
    EditorGroups (0.46)
    Scratch (1.10)
    krasa.CpuUsageIndicator (1.15)
    EclipseCodeFormatter (23.1.223.000.0-Eclipse_2023-03)
    VisualVMLauncher (1.21.211.6085.0)
    String Manipulation (9.7.1)
    ChatGPT (2.1.10-222.231)
    nb-mind-map-idea (1.6.2)
    MavenRunHelper (4.23.222.2964.0)
    GrepConsole (12.16.211.6693.0)
    PlantUML integration (5.23.0)

Kotlin: 231-1.8.20-IJ8770.17
```

**Comment by vaple** [comment]
```
IntelliJ IDEA 2023.1 (Ultimate Edition)
Build #IU-231.8109.175, built on March 28, 2023

Runtime version: 17.0.6+10-b829.5 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 20
Registry:
    ide.intellij.laf.enable.animation=true
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    editor.minimap.enabled=true

Non-Bundled Plugins:
    org.jetbrains.toolbox-enterprise-client (10000.0.10-ij212)
    com.mallowigi.idea (20.0.0)
    Statistic (4.2.7)
    com.starxg.mybatis-log-plugin-free (1.3.0)
    GsonFormatPlus (1.6.1)
    com.github.setial (4.0.2)
    com.bigmy (1.0)
    GrepConsole (10.0.201.4515.0)
    spring-assistant-@valueToYml (2022.3.3-1)
    MavenRunHelper (4.15.212.000.0)
    com.mallowigi (90.0.0)
    com.intellij.bigdatatools (231.8109.175)
    MetricsReloaded (1.12)
    com.ccnode.codegenerator.MyBatisCodeHelperPro (3.1.8)

Kotlin: 231-1.8.20-IJ8109.175
```

**Comment by krasa** [comment]
Your GrepConsole is super old, from Apr 26, 2020

**Comment by vaple** [comment]
there are some problems with idea plugin marketplace,update from web and it works,thanks
![image](https://user-images.githubusercontent.com/46566508/234216559-fe35ea13-4f56-401c-9a85-5fb8ae14709f.png)
