### ISSUE TITLE
Causes "Critical issue" with GoLand Nightly

### ISSUE THREAD

**Issue by topia** [krasa/GrepConsole#287]
**Describe the bug**
Failed to launch GoLand Nightly IDE with GrepConsole plugin.

**To Reproduce**
1. Install GrepConsole 12.21.0-IJ2021.1
2. Restart GoLand
4. See `Start Failed`

**Expected behavior**
GoLand should run normally

**Screenshots**
```
Internal error. Please refer to https://jb.gg/ide/critical-startup-errors

java.lang.NoClassDefFoundError: org/apache/commons/lang/builder/EqualsBuilder
    at krasa.grepconsole.model.DomainObject.equals(DomainObject.java:13)
    at java.base/java.util.Objects.equals(Objects.java:64)
    at java.base/java.util.ArrayList.equalsArrayList(ArrayList.java:561)
    at java.base/java.util.ArrayList.equals(ArrayList.java:529)
    at com.intellij.openapi.util.Comparing.equal(Comparing.java:32)
    at com.intellij.util.xmlb.SkipDefaultsSerializationFilter.equal(SkipDefaultsSerializationFilter.java:63)
    at com.intellij.util.xmlb.SkipDefaultsSerializationFilter.equal(SkipDefaultsSerializationFilter.java:32)
    at com.intellij.util.xmlb.BeanBinding.serializePropertyInto(BeanBinding.java:107)
    at com.intellij.util.xmlb.BeanBinding.serializeInto(BeanBinding.java:92)
    at com.intellij.serialization.xml.KotlinAwareBeanBinding.serializeInto(KotlinAwareBeanBinding.kt:39)
    at com.intellij.util.xmlb.BeanBinding.serialize(BeanBinding.java:79)
    at com.intellij.util.xmlb.AbstractCollectionBinding.serializeItem(AbstractCollectionBinding.java:227)
    at com.intellij.util.xmlb.AbstractCollectionBinding.serialize(AbstractCollectionBinding.java:144)
    at com.intellij.util.xmlb.OptionTagBinding.serialize(OptionTagBinding.java:64)
    at com.intellij.util.xmlb.BasePrimitiveBinding.serialize(BasePrimitiveBinding.java:43)
    at com.intellij.util.xmlb.BeanBinding.serializePropertyInto(BeanBinding.java:127)
    at com.intellij.util.xmlb.BeanBinding.serializeInto(BeanBinding.java:92)
    at com.intellij.serialization.xml.KotlinAwareBeanBinding.serializeInto(KotlinAwareBeanBinding.kt:39)
    at com.intellij.util.xmlb.BeanBinding.serialize(BeanBinding.java:83)
    at com.intellij.configurationStore.JdomSerializerImpl.serialize(xmlSerializer.kt:51)
    at com.intellij.configurationStore.XmlSerializer.serialize(xmlSerializer.kt:25)
    at com.intellij.configurationStore.XmlSerializer.serialize$default(xmlSerializer.kt:22)
    at com.intellij.configurationStore.SaveSessionProducerBaseKt.serializeState(SaveSessionProducerBase.kt:46)
    at com.intellij.configurationStore.StateGetterImpl.archiveState(StorageBaseEx.kt:87)
    at com.intellij.configurationStore.ComponentStoreImpl.doInitComponent(ComponentStoreImpl.kt:491)
    at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:409)
    at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:131)
    at com.intellij.configurationStore.ComponentStoreWithExtraComponents.initComponent(ComponentStoreWithExtraComponents.kt:48)
    at com.intellij.serviceContainer.ComponentManagerImpl.initializeComponent$intellij_platform_serviceContainer(ComponentManagerImpl.kt:583)
    at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:41)
    at com.intellij.serviceContainer.BaseComponentAdapter.doCreateInstance(BaseComponentAdapter.kt:176)
    at com.intellij.serviceContainer.BaseComponentAdapter.createInstance(BaseComponentAdapter.kt:155)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:97)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:81)
    at com.intellij.serviceContainer.ComponentManagerImpl$createInitOldComponentsTask$1.invoke(ComponentManagerImpl.kt:420)
    at com.intellij.serviceContainer.ComponentManagerImpl$createInitOldComponentsTask$1.invoke(ComponentManagerImpl.kt:418)
    at com.intellij.platform.ide.bootstrap.AppServicePreloadingKt$postAppRegistered$3$1.invokeSuspend(appServicePreloading.kt:176)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
    at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
    at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
    at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:320)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
    at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang.builder.EqualsBuilder PluginClassLoader(plugin=PluginDescriptor(name=Grep Console, id=GrepConsole, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\GoLand2023.3\plugins\GrepConsole, version=12.21.0-IJ2021.1, package=null, isBundled=false), packagePrefix=null, state=active)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:156)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
    ... 53 more

-----
Your JRE: 17.0.8.1+7-b1063.1 amd64 (JetBrains s.r.o.)
C:\Users\Topia\AppData\Local\Programs\GoLand\jbr
```

**Environment :**
GoLand 2023.3 EAP
Build #GO-233.8580, built on September 28, 2023

**Additional context**
- As you know, I'm using nightly/EAP; No need to fix it quickly.
- Add `GrepConsole` to `disabled_plugins.txt` for disabling the plugin if you encounter this issue.

**Comment by krasa** [comment]
Thanks!
