### ISSUE TITLE
Idea 2024.2 

### ISSUE THREAD

**Issue by sdandroid** [krasa/GrepConsole#310]
crash Idea 2024.2  start.

**Comment by krasa** [comment]
???

**Comment by sdandroid** [comment]
IDEA 2024.2 version install this plugin  will start fail.
```
	at krasa.grepconsole.integration.LookAndFeelListener.lookAndFeelChanged(LookAndFeelListener.java:29)
	at krasa.grepconsole.integration.LookAndFeelListener.<init>(LookAndFeelListener.java:23)
	at krasa.grepconsole.plugin.GrepConsoleApplicationComponent.<init>(GrepConsoleApplicationComponent.java:36)
2024-08-08 15:19:27,987 [    708]   INFO - STDERR - 	at krasa.grepconsole.integration.LookAndFeelListener.lookAndFeelChanged(LookAndFeelListener.java:29)
2024-08-08 15:19:27,988 [    709]   INFO - STDERR - 	at krasa.grepconsole.integration.LookAndFeelListener.<init>(LookAndFeelListener.java:23)
2024-08-08 15:19:27,988 [    709]   INFO - STDERR - 	at krasa.grepconsole.plugin.GrepConsoleApplicationComponent.<init>(GrepConsoleApplicationComponent.java:36)
2024-08-08 15:19:28,002 [    723]   INFO - STDERR - 	at krasa.grepconsole.integration.LookAndFeelListener.lookAndFeelChanged(LookAndFeelListener.java:29)
2024-08-08 15:19:28,002 [    723]   INFO - STDERR - 	at krasa.grepconsole.integration.LookAndFeelListener.<init>(LookAndFeelListener.java:23)
2024-08-08 15:19:28,003 [    724]   INFO - STDERR - 	at krasa.grepconsole.plugin.GrepConsoleApplicationComponent.<init>(GrepConsoleApplicationComponent.java:36)
2024-08-08 15:19:28,008 [    729]   INFO - STDERR - 	at krasa.grepconsole.integration.LookAndFeelListener.lookAndFeelChanged(LookAndFeelListener.java:29)
2024-08-08 15:19:28,008 [    729]   INFO - STDERR - 	at krasa.grepconsole.integration.LookAndFeelListener.<init>(LookAndFeelListener.java:23)
2024-08-08 15:19:28,008 [    729]   INFO - STDERR - 	at krasa.grepconsole.plugin.GrepConsoleApplicationComponent.<init>(GrepConsoleApplicationComponent.java:36)
2024-08-08 15:19:28,013 [    734]   INFO - STDERR - 	at krasa.grepconsole.integration.LookAndFeelListener.lookAndFeelChanged(LookAndFeelListener.java:29)
2024-08-08 15:19:28,013 [    734]   INFO - STDERR - 	at krasa.grepconsole.integration.LookAndFeelListener.<init>(LookAndFeelListener.java:23)
2024-08-08 15:19:28,013 [    734]   INFO - STDERR - 	at krasa.grepconsole.plugin.GrepConsoleApplicationComponent.<init>(GrepConsoleApplicationComponent.java:36)
2024-08-08 15:19:28,020 [    741]   INFO - STDERR - 	at krasa.grepconsole.integration.LookAndFeelListener.lookAndFeelChanged(LookAndFeelListener.java:29)
2024-08-08 15:19:28,020 [    741]   INFO - STDERR - 	at krasa.grepconsole.integration.LookAndFeelListener.<init>(LookAndFeelListener.java:23)
2024-08-08 15:19:28,020 [    741]   INFO - STDERR - 	at krasa.grepconsole.plugin.GrepConsoleApplicationComponent.<init>(GrepConsoleApplicationComponent.java:36)
2024-08-08 15:19:28,027 [    748]   INFO - STDERR - 	at krasa.grepconsole.integration.LookAndFeelListener.lookAndFeelChanged(LookAndFeelListener.java:29)
2024-08-08 15:19:28,027 [    748]   INFO - STDERR - 	at krasa.grepconsole.integration.LookAndFeelListener.<init>(LookAndFeelListener.java:23)
2024-08-08 15:19:28,027 [    748]   INFO - STDERR - 	at krasa.grepconsole.plugin.GrepConsoleApplicationComponent.<init>(GrepConsoleApplicationComponent.java:36)
2024-08-08 15:19:28,038 [    759]   INFO - STDERR - 	at krasa.grepconsole.integration.LookAndFeelListener.lookAndFeelChanged(LookAndFeelListener.java:29)
2024-08-08 15:19:28,038 [    759]   INFO - STDERR - 	at krasa.grepconsole.integration.LookAndFeelListener.<init>(LookAndFeelListener.java:23)
2024-08-08 15:19:28,038 [    759]   INFO - STDERR - 	at krasa.grepconsole.plugin.GrepConsoleApplicationComponent.<init>(GrepConsoleApplicationComponent.java:36)
2024-08-08 15:19:28,059 [    780]   INFO - STDERR - 	at krasa.grepconsole.integration.LookAndFeelListener.lookAndFeelChanged(LookAndFeelListener.java:29)
2024-08-08 15:19:28,059 [    780]   INFO - STDERR - 	at krasa.grepconsole.integration.LookAndFeelListener.<init>(LookAndFeelListener.java:23)
2024-08-08 15:19:28,059 [    780]   INFO - STDERR - 	at krasa.grepconsole.plugin.GrepConsoleApplicationComponent.<init>(GrepConsoleApplicationComponent.java:36)
2024-08-08 15:19:28,068 [    789]   INFO - STDERR - 	at krasa.grepconsole.integration.LookAndFeelListener.lookAndFeelChanged(LookAndFeelListener.java:29)
2024-08-08 15:19:28,068 [    789]   INFO - STDERR - 	at krasa.grepconsole.integration.LookAndFeelListener.<init>(LookAndFeelListener.java:23)
2024-08-08 15:19:28,068 [    789]   INFO - STDERR - 	at krasa.grepconsole.plugin.GrepConsoleApplicationComponent.<init>(GrepConsoleApplicationComponent.java:36)
2024-08-08 15:19:28,071 [    792]   INFO - STDERR - 	at krasa.grepconsole.integration.LookAndFeelListener.lookAndFeelChanged(LookAndFeelListener.java:29)
2024-08-08 15:19:28,071 [    792]   INFO - STDERR - 	at krasa.grepconsole.integration.LookAndFeelListener.<init>(LookAndFeelListener.java:23)
2024-08-08 15:19:28,071 [    792]   INFO - STDERR - 	at krasa.grepconsole.plugin.GrepConsoleApplicationComponent.<init>(GrepConsoleApplicationComponent.java:36)
2024-08-08 15:19:28,074 [    795]   INFO - STDERR - 	at krasa.grepconsole.integration.LookAndFeelListener.lookAndFeelChanged(LookAndFeelListener.java:29)
2024-08-08 15:19:28,074 [    795]   INFO - STDERR - 	at krasa.grepconsole.integration.LookAndFeelListener.<init>(LookAndFeelListener.java:23)
2024-08-08 15:19:28,074 [    795]   INFO - STDERR - 	at krasa.grepconsole.plugin.GrepConsoleApplicationComponent.<init>(GrepConsoleApplicationComponent.java:36)
2024-08-08 15:19:28,078 [    799]   INFO - STDERR - 	at krasa.grepconsole.integration.LookAndFeelListener.lookAndFeelChanged(LookAndFeelListener.java:29)
2024-08-08 15:19:28,078 [    799]   INFO - STDERR - 	at krasa.grepconsole.integration.LookAndFeelListener.<init>(LookAndFeelListener.java:23)
2024-08-08 15:19:28,078 [    799]   INFO - STDERR - 	at krasa.grepconsole.plugin.GrepConsoleApplicationComponent.<init>(GrepConsoleApplicationComponent.java:36)
2024-08-08 15:19:28,083 [    804]   INFO - STDERR - 	at krasa.grepconsole.integration.LookAndFeelListener.lookAndFeelChanged(LookAndFeelListener.java:29)
2024-08-08 15:19:28,083 [    804]   INFO - STDERR - 	at krasa.grepconsole.integration.LookAndFeelListener.<init>(LookAndFeelListener.java:23)
2024-08-08 15:19:28,083 [    804]   INFO - STDERR - 	at krasa.grepconsole.plugin.GrepConsoleApplicationComponent.<init>(GrepConsoleApplicationComponent.java:36)
2024-08-08 15:19:28,086 [    807]   INFO - STDERR - 	at krasa.grepconsole.integration.LookAndFeelListener.lookAndFeelChanged(LookAndFeelListener.java:29)
2024-08-08 15:19:28,086 [    807]   INFO - STDERR - 	at krasa.grepconsole.integration.LookAndFeelListener.<init>(LookAndFeelListener.java:23)
2024-08-08 15:19:28,086 [    807]   INFO - STDERR - 	at krasa.grepconsole.plugin.GrepConsoleApplicationComponent.<init>(GrepConsoleApplicationComponent.java:36)
2024-08-08 15:19:28,088 [    809]   INFO - STDERR - 	at krasa.grepconsole.integration.LookAndFeelListener.lookAndFeelChanged(LookAndFeelListener.java:29)
2024-08-08 15:19:28,088 [    809]   INFO - STDERR - 	at krasa.grepconsole.integration.LookAndFeelListener.<init>(LookAndFeelListener.java:23)
2024-08-08 15:19:28,088 [    809]   INFO - STDERR - 	at krasa.grepconsole.plugin.GrepConsoleApplicationComponent.<init>(GrepConsoleApplicationComponent.java:36)
2024-08-08 15:19:28,128 [    849]   INFO - STDERR - 	at krasa.grepconsole.integration.LookAndFeelListener.lookAndFeelChanged(LookAndFeelListener.java:29)
2024-08-08 15:19:28,128 [    849]   INFO - STDERR - 	at krasa.grepconsole.integration.LookAndFeelListener.<init>(LookAndFeelListener.java:23)
2024-08-08 15:19:28,128 [    849]   INFO - STDERR - 	at krasa.grepconsole.plugin.GrepConsoleApplicationComponent.<init>(GrepConsoleApplicationComponent.java:36)
	at krasa.grepconsole.integration.LookAndFeelListener.lookAndFeelChanged(LookAndFeelListener.java:29)
	at krasa.grepconsole.integration.LookAndFeelListener.<init>(LookAndFeelListener.java:23)
	at krasa.grepconsole.plugin.GrepConsoleApplicationComponent.<init>(GrepConsoleApplicationComponent.java:36)

```
```
2024-08-08 15:21:03,120 [   1318]   INFO - STDERR - java.lang.NullPointerException: Cannot invoke "javax.swing.UIDefaults.getBoolean(Object)" because "defaults" is null
2024-08-08 15:21:03,120 [   1318]   INFO - STDERR - 	at java.desktop/javax.swing.plaf.synth.SynthLookAndFeel$AATextListener.propertyChange(SynthLookAndFeel.java:894)
2024-08-08 15:21:03,120 [   1318]   INFO - STDERR - 	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:343)
2024-08-08 15:21:03,120 [   1318]   INFO - STDERR - 	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:336)
2024-08-08 15:21:03,120 [   1318]   INFO - STDERR - 	at java.desktop/java.awt.Toolkit$DesktopPropertyChangeSupport$1.run(Toolkit.java:2330)
2024-08-08 15:21:03,120 [   1318]   INFO - STDERR - 	at java.desktop/java.awt.Toolkit$DesktopPropertyChangeSupport.firePropertyChange(Toolkit.java:2340)
2024-08-08 15:21:03,120 [   1318]   INFO - STDERR - 	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:268)
2024-08-08 15:21:03,120 [   1318]   INFO - STDERR - 	at java.desktop/java.awt.Toolkit.setDesktopProperty(Toolkit.java:1601)
2024-08-08 15:21:03,120 [   1318]   INFO - STDERR - 	at java.desktop/sun.awt.SunToolkit.fireDesktopFontPropertyChanges(SunToolkit.java:1723)
2024-08-08 15:21:03,120 [   1318]   INFO - STDERR - 	at java.desktop/sun.awt.SunToolkit.setAAFontSettingsCondition(SunToolkit.java:1768)
2024-08-08 15:21:03,120 [   1318]   INFO - STDERR - 	at java.desktop/sun.swing.SwingUtilities2.putAATextInfo(SwingUtilities2.java:177)
2024-08-08 15:21:03,120 [   1318]   INFO - STDERR - 	at java.desktop/javax.swing.plaf.metal.MetalLookAndFeel.initComponentDefaults(MetalLookAndFeel.java:1530)
2024-08-08 15:21:03,120 [   1318]   INFO - STDERR - 	at com.intellij.ide.ui.laf.IdeaLaf.initComponentDefaults(IdeaLaf.kt:25)
2024-08-08 15:21:03,120 [   1318]   INFO - STDERR - 	at java.desktop/javax.swing.plaf.basic.BasicLookAndFeel.getDefaults(BasicLookAndFeel.java:161)
2024-08-08 15:21:03,120 [   1318]   INFO - STDERR - 	at java.desktop/javax.swing.plaf.metal.MetalLookAndFeel.getDefaults(MetalLookAndFeel.java:1564)
2024-08-08 15:21:03,120 [   1318]   INFO - STDERR - 	at com.intellij.platform.ide.bootstrap.UiKt.initLafAndScale$lambda$1(ui.kt:110)
2024-08-08 15:21:03,120 [   1318]   INFO - STDERR - 	at com.intellij.ui.scale.JBUIScale.computeSystemFontData(JBUIScale.kt:127)
2024-08-08 15:21:03,120 [   1318]   INFO - STDERR - 	at com.intellij.ui.scale.JBUIScale.preload(JBUIScale.kt:63)
2024-08-08 15:21:03,120 [   1318]   INFO - STDERR - 	at com.intellij.platform.ide.bootstrap.UiKt.initLafAndScale(ui.kt:109)
2024-08-08 15:21:03,120 [   1318]   INFO - STDERR - 	at com.intellij.platform.ide.bootstrap.UiKt.access$initLafAndScale(ui.kt:1)
2024-08-08 15:21:03,120 [   1318]   INFO - STDERR - 	at com.intellij.platform.ide.bootstrap.UiKt$initLafAndScale$1.invokeSuspend(ui.kt)
2024-08-08 15:21:03,120 [   1318]   INFO - STDERR - 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2024-08-08 15:21:03,120 [   1318]   INFO - STDERR - 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
2024-08-08 15:21:03,120 [   1318]   INFO - STDERR - 	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
2024-08-08 15:21:03,120 [   1318]   INFO - STDERR - 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
2024-08-08 15:21:03,120 [   1318]   INFO - STDERR - 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
2024-08-08 15:21:03,120 [   1318]   INFO - STDERR - 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
2024-08-08 15:21:03,120 [   1318]   INFO - STDERR - 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
2024-08-08 15:21:03,120 [   1318]   INFO - STDERR - 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
2024-08-08 15:21:03,120 [   1318]   INFO - STDERR - 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:750)
2024-08-08 15:21:03,120 [   1318]   INFO - STDERR - 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:320)
2024-08-08 15:21:03,120 [   1318]   INFO - STDERR - 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
2024-08-08 15:21:03,120 [   1318]   INFO - STDERR - 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
2024-08-08 15:21:03,120 [   1318]   INFO - STDERR - 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
2024-08-08 15:21:03,120 [   1318]   INFO - STDERR - 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
2024-08-08 15:21:03,120 [   1318]   INFO - STDERR - 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
2024-08-08 15:21:03,120 [   1318]   INFO - STDERR - 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

````

**Comment by krasa** [comment]
Strange. You can update.
