### ISSUE TITLE
TRIM output

### ISSUE THREAD

**Issue by OleksandrKucherenko** [krasa/GrepConsole#47]
Will be nice to have a feature that allows to replace pattern in log by something else.

Example (Original Output): 
06-12 10:02:40.561  12752-12752/mobi.mobiletech.apps.android.netcom I/WebRequests﹕ [00001] WebRequests.executeOnComplete: #1114840240. All requests are done!

After modification:
02:40.561 I/WebRequests﹕ [00001] WebRequests.executeOnComplete: #1114840240. All requests are done!

Special pattern will allow to TRIM output line by removing (reduce) from it redundant information, making logs line more clear.

**Comment by krasa** [comment]
If you could provide some snippet of that replacing functionality, I could integrate it into the plugin.
But it would be easier to just configure your logger.

**Comment by kookob** [comment]
Hi, I have a demand like this:
when the mybatis output log like:

2016-10-01 01:50:43 [com.test.dao.getHotArticle]-[DEBUG] ==>  Preparing: select * from article where id = ?
2016-10-01 01:50:43 [com.test.dao.getHotArticle]-[DEBUG] ==> Parameters: 123(Integer)

I want to append a new line log behind "Parameters: 123(Integer) "  like this
select * from article where id = 123

What can I do to achieve it?

And when i run the GrepInputFilterTest.java
It take an error blow:

java.lang.ExceptionInInitializerError
	at krasa.grepconsole.filter.GrepHighlightFilter.prepareResult(GrepHighlightFilter.java:66)
	at krasa.grepconsole.filter.GrepHighlightFilter.applyFilter(GrepHighlightFilter.java:42)
	at krasa.grepconsole.filter.GrepHighlightFilterTest.testCombinations(GrepHighlightFilterTest.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.IllegalArgumentException: Argument for @NotNull parameter 'componentManager' of com/intellij/openapi/components/ServiceManager.doGetService must not be null
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:37)
	at com.intellij.openapi.editor.colors.EditorColorsManager.getInstance(EditorColorsManager.java:29)
	at com.intellij.execution.filters.Filter$Result.<clinit>(Filter.java:42)
	... 30 more


Process finished with exit code -1
============
I Position the code is:
(GrepHighlightFilter.java:66)
if (resultItemList != null) {
	result = new Result(resultItemList);
	result.setNextAction(NextAction.CONTINUE_FILTERING);
}

**Comment by kvenn** [comment]
Is this possible to do? I have a similar requirement:

I have this at the beginning of every log line:

```
[INFO][2023-08-26 13:38:43.462862] ...
[DEBUG][2023-08-26 13:38:43.462862] ...
```

Would it be possible to replace/rewrite it to:

```
[I][13:38:43.4628]...
```

**Comment by krasa** [comment]
sure, that's easy
![image](https://github.com/krasa/GrepConsole/assets/1160875/02ed0285-e2a5-41d5-bc5a-eb62c9e0b570)

either using own plugin https://github.com/krasa/GrepConsole-Extension-Example/tree/shortener 
or [live plugin](https://plugins.jetbrains.com/plugin/7282-liveplugin)  script:

```
import org.jetbrains.annotations.Nullable

import java.util.function.Function
import java.util.regex.Matcher
import java.util.regex.Pattern

import com.intellij.ide.plugins.IdeaPluginDescriptorImpl
import com.intellij.ide.plugins.PluginManager
import com.intellij.openapi.extensions.PluginId

import java.util.function.Function

import static com.intellij.openapi.util.text.StringUtil.newBombedCharSequence
import static liveplugin.PluginUtil.*

/**
 https://github.com/dkandalov/live-plugin/blob/master/src/plugin-util-groovy/liveplugin/PluginUtil.groovy
 */

registerFunction("shorten", new Function<String, String>() {
    public static Pattern pattern = Pattern.compile("^\\[(\\w)\\w++\\]\\[\\d{4}-\\d{2}-\\d{2} (\\d{2}:\\d{2}:\\d{2}.\\d{4})\\d+] ");

    /** - The text will never be empty, it may or may not end with a newline - \n
     *  - It is possible that the stream will flush prematurely and the text will be incomplete: IDEA-70016
     *  - Return null to remove the line
     *  - Processing blocks application output stream, make sure to limit the length and processing time when needed using #limitAndCutNewline
     **/
    @Override
    String apply(String text) {
        try {
            CharSequence textForMatching = limitAndCutNewline(text, 50, 1000);

            Matcher matcher = pattern.matcher(textForMatching);
            if (matcher.find()) {
                String level = matcher.group(1);
                String time = matcher.group(2);
                return "[" + level + "][" + time + "]" + text.substring(matcher.end());
            }
            return text;

        } catch (com.intellij.openapi.progress.ProcessCanceledException ex) {
            show("Processing took too long for: " + text)
        }
        return text
    }
})



static Class<?> getExtensionManager() {
    IdeaPluginDescriptorImpl descriptor = PluginManager.getPlugin(PluginId.getId("GrepConsole"))
    return descriptor.getPluginClassLoader().loadClass("krasa.grepconsole.plugin.ExtensionManager");
}

static void registerFunction(String functionName, Function<String, String> function) {
    Class<?> clazz = getExtensionManager()

    clazz.getMethod("registerFunction", String.class, Function.class)
            .invoke(null, functionName, function);

    liveplugin.PluginUtil.show("'" + functionName + "' registered")
}

static Object unregisterFunction(Class<?> clazz, String functionName) {
    clazz.getMethod("unregisterFunction", String.class).invoke(null, functionName)
    liveplugin.PluginUtil.show("'" + functionName + "' unregistered")
}


static CharSequence limitAndCutNewline(String text, int maxLength, milliseconds) {
    int endIndex = text.length()
    if (text.endsWith("\n")) {
        --endIndex
    }
    if (maxLength >= 0) {
        endIndex = Math.min(endIndex, maxLength)
    }
    def substring = text.substring(0, endIndex)

    if (milliseconds > 0) {
        return newBombedCharSequence(substring, milliseconds)
    }
    return substring
}
```

**Comment by kvenn** [comment]
So cool! Thank you for the fast response.

I didn't understand how extensions work, but now I get it.

"Create LivePlugin example" didn't work like the gif you sent, so I created one myself.
I was able to run it and select `shorten` from the dropdown.

It doesn't seem like it's working, though. But I'm happy to try to debug the code myself. Do you have any recommendations for how I can tell if I configured it correctly? And is it possible to set breakpoints in the groovy file?
