### ISSUE TITLE
java.lang.NoClassDefFoundError: javax/media/ControllerListener

### ISSUE THREAD

**Issue by bobwenx** [krasa/GrepConsole#49]
JVM: Apple JVM 1.6
OS: OS X 10.10
IDEA: 14.1.4

```java
Plugin 'GrepConsole' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

java.lang.NoClassDefFoundError: javax/media/ControllerListener
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:471)
    at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:259)
    at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:255)
    at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:231)
    at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:124)
    at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:77)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2484)
    at java.lang.Class.privateGetPublicMethods(Class.java:2604)
    at java.lang.Class.getMethods(Class.java:1446)
    at com.intellij.util.xmlb.BeanBinding.collectPropertyAccessors(BeanBinding.java:278)
    at com.intellij.util.xmlb.BeanBinding.getAccessors(BeanBinding.java:267)
    at com.intellij.util.xmlb.BeanBinding.init(BeanBinding.java:69)
    at com.intellij.util.xmlb.XmlSerializerImpl.getClassBinding(XmlSerializerImpl.java:117)
    at com.intellij.util.xmlb.XmlSerializerImpl.getBinding(XmlSerializerImpl.java:73)
    at com.intellij.util.xmlb.AbstractCollectionBinding.getElementBindings(AbstractCollectionBinding.java:68)
    at com.intellij.util.xmlb.AbstractCollectionBinding.getElementBinding(AbstractCollectionBinding.java:93)
    at com.intellij.util.xmlb.AbstractCollectionBinding.deserializeItem(AbstractCollectionBinding.java:192)
    at com.intellij.util.xmlb.AbstractCollectionBinding.deserializeSingle(AbstractCollectionBinding.java:239)
    at com.intellij.util.xmlb.AbstractCollectionBinding.deserializeList(AbstractCollectionBinding.java:158)
    at com.intellij.util.xmlb.Binding.deserializeList(Binding.java:60)
    at com.intellij.util.xmlb.OptionTagBinding.deserialize(OptionTagBinding.java:103)
    at com.intellij.util.xmlb.BeanBinding.deserializeInto(BeanBinding.java:219)
    at com.intellij.util.xmlb.BeanBinding.deserialize(BeanBinding.java:127)
    at com.intellij.util.xmlb.AbstractCollectionBinding.deserializeItem(AbstractCollectionBinding.java:205)
    at com.intellij.util.xmlb.AbstractCollectionBinding.deserializeSingle(AbstractCollectionBinding.java:239)
    at com.intellij.util.xmlb.AbstractCollectionBinding.deserializeList(AbstractCollectionBinding.java:158)
    at com.intellij.util.xmlb.Binding.deserializeList(Binding.java:60)
    at com.intellij.util.xmlb.OptionTagBinding.deserialize(OptionTagBinding.java:103)
    at com.intellij.util.xmlb.BeanBinding.deserializeInto(BeanBinding.java:219)
    at com.intellij.util.xmlb.BeanBinding.deserialize(BeanBinding.java:127)
    at com.intellij.util.xmlb.AbstractCollectionBinding.deserializeItem(AbstractCollectionBinding.java:205)
    at com.intellij.util.xmlb.AbstractCollectionBinding.deserializeSingle(AbstractCollectionBinding.java:239)
    at com.intellij.util.xmlb.AbstractCollectionBinding.deserializeList(AbstractCollectionBinding.java:158)
    at com.intellij.util.xmlb.Binding.deserializeList(Binding.java:60)
    at com.intellij.util.xmlb.OptionTagBinding.deserialize(OptionTagBinding.java:103)
    at com.intellij.util.xmlb.BeanBinding.deserializeInto(BeanBinding.java:219)
    at com.intellij.util.xmlb.BeanBinding.deserialize(BeanBinding.java:127)
    at com.intellij.util.xmlb.XmlSerializer.deserialize(XmlSerializer.java:68)
    at com.intellij.openapi.components.impl.stores.DefaultStateSerializer.deserializeState(DefaultStateSerializer.java:59)
    at com.intellij.openapi.components.impl.stores.StateStorageBase.deserializeState(StateStorageBase.java:45)
    at com.intellij.openapi.components.impl.stores.StateStorageBase.getState(StateStorageBase.java:40)
    at com.intellij.openapi.components.impl.stores.ComponentStoreImpl.a(ComponentStoreImpl.java:318)
    at com.intellij.openapi.components.impl.stores.ComponentStoreImpl.initComponent(ComponentStoreImpl.java:75)
    at com.intellij.openapi.application.impl.ApplicationImpl.initializeComponent(ApplicationImpl.java:177)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:566)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:610)
    at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:245)
    at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:211)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponent(ComponentManagerImpl.java:125)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponent(ApplicationImpl.java:354)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:116)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:87)
    at com.intellij.openapi.components.impl.stores.ApplicationStoreImpl.load(ApplicationStoreImpl.java:101)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:499)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:481)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:170)
    at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:62)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:676)
    at java.awt.EventQueue$2.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:362)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: java.lang.ClassNotFoundException: javax.media.ControllerListener PluginClassLoader[GrepConsole, 5.8.134.1007]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    ... 78 more
```

**Comment by krasa** [comment]
Strange, I would suggest reinstalling the plugin.

**Comment by bobwenx** [comment]
after reinstalling the plugin, i work fine without problems. it seems i downloaded a bad zip file.

**Comment by bobwenx** [comment]
i am wrong, it still not working. the IDEA just swallow the exception message, and i still not able to use it in IDE's console plane.

exceptions in IDEA startup log file:
```java
java.lang.RuntimeException: com.intellij.ide.plugins.PluginManager$StartupAbortedException: com.intellij.diagnostic.PluginException: javax/media/ControllerListener [Plugin: GrepConsole]
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:178)
	at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:62)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:362)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: com.intellij.ide.plugins.PluginManager$StartupAbortedException: com.intellij.diagnostic.PluginException: javax/media/ControllerListener [Plugin: GrepConsole]
	at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:245)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.handleInitComponentError(PlatformComponentManagerImpl.java:39)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:590)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:610)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:245)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:211)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponent(ComponentManagerImpl.java:125)
	at com.intellij.openapi.application.impl.ApplicationImpl.createComponent(ApplicationImpl.java:354)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:116)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:87)
	at com.intellij.openapi.components.impl.stores.ApplicationStoreImpl.load(ApplicationStoreImpl.java:101)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:499)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:481)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:170)
	... 16 more
Caused by: com.intellij.diagnostic.PluginException: javax/media/ControllerListener [Plugin: GrepConsole]
	... 30 more
Caused by: java.lang.NoClassDefFoundError: javax/media/ControllerListener
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:471)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:259)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:255)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:231)
	at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:124)
	at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:77)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2484)
	at java.lang.Class.privateGetPublicMethods(Class.java:2604)
	at java.lang.Class.getMethods(Class.java:1446)
	at com.intellij.util.xmlb.BeanBinding.collectPropertyAccessors(BeanBinding.java:278)
	at com.intellij.util.xmlb.BeanBinding.getAccessors(BeanBinding.java:267)
	at com.intellij.util.xmlb.BeanBinding.init(BeanBinding.java:69)
	at com.intellij.util.xmlb.XmlSerializerImpl.getClassBinding(XmlSerializerImpl.java:117)
	at com.intellij.util.xmlb.XmlSerializerImpl.getBinding(XmlSerializerImpl.java:73)
	at com.intellij.util.xmlb.AbstractCollectionBinding.getElementBindings(AbstractCollectionBinding.java:68)
	at com.intellij.util.xmlb.AbstractCollectionBinding.getElementBinding(AbstractCollectionBinding.java:93)
	at com.intellij.util.xmlb.AbstractCollectionBinding.deserializeItem(AbstractCollectionBinding.java:192)
	at com.intellij.util.xmlb.AbstractCollectionBinding.deserializeSingle(AbstractCollectionBinding.java:239)
	at com.intellij.util.xmlb.AbstractCollectionBinding.deserializeList(AbstractCollectionBinding.java:158)
	at com.intellij.util.xmlb.Binding.deserializeList(Binding.java:60)
	at com.intellij.util.xmlb.OptionTagBinding.deserialize(OptionTagBinding.java:103)
	at com.intellij.util.xmlb.BeanBinding.deserializeInto(BeanBinding.java:219)
	at com.intellij.util.xmlb.BeanBinding.deserialize(BeanBinding.java:127)
	at com.intellij.util.xmlb.AbstractCollectionBinding.deserializeItem(AbstractCollectionBinding.java:205)
	at com.intellij.util.xmlb.AbstractCollectionBinding.deserializeSingle(AbstractCollectionBinding.java:239)
	at com.intellij.util.xmlb.AbstractCollectionBinding.deserializeList(AbstractCollectionBinding.java:158)
	at com.intellij.util.xmlb.Binding.deserializeList(Binding.java:60)
	at com.intellij.util.xmlb.OptionTagBinding.deserialize(OptionTagBinding.java:103)
	at com.intellij.util.xmlb.BeanBinding.deserializeInto(BeanBinding.java:219)
	at com.intellij.util.xmlb.BeanBinding.deserialize(BeanBinding.java:127)
	at com.intellij.util.xmlb.AbstractCollectionBinding.deserializeItem(AbstractCollectionBinding.java:205)
	at com.intellij.util.xmlb.AbstractCollectionBinding.deserializeSingle(AbstractCollectionBinding.java:239)
	at com.intellij.util.xmlb.AbstractCollectionBinding.deserializeList(AbstractCollectionBinding.java:158)
	at com.intellij.util.xmlb.Binding.deserializeList(Binding.java:60)
	at com.intellij.util.xmlb.OptionTagBinding.deserialize(OptionTagBinding.java:103)
	at com.intellij.util.xmlb.BeanBinding.deserializeInto(BeanBinding.java:219)
	at com.intellij.util.xmlb.BeanBinding.deserialize(BeanBinding.java:127)
	at com.intellij.util.xmlb.XmlSerializer.deserialize(XmlSerializer.java:68)
	at com.intellij.openapi.components.impl.stores.DefaultStateSerializer.deserializeState(DefaultStateSerializer.java:59)
	at com.intellij.openapi.components.impl.stores.StateStorageBase.deserializeState(StateStorageBase.java:45)
	at com.intellij.openapi.components.impl.stores.StateStorageBase.getState(StateStorageBase.java:40)
	at com.intellij.openapi.components.impl.stores.ComponentStoreImpl.a(ComponentStoreImpl.java:318)
	at com.intellij.openapi.components.impl.stores.ComponentStoreImpl.initComponent(ComponentStoreImpl.java:75)
	at com.intellij.openapi.application.impl.ApplicationImpl.initializeComponent(ApplicationImpl.java:177)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:566)
	... 27 more
Caused by: java.lang.ClassNotFoundException: javax.media.ControllerListener PluginClassLoader[GrepConsole, 5.8.134.1007]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	... 78 more
```

BTW: i was able to install `grepConsole` in AppCode.

**Comment by bobwenx** [comment]
Forget my previous post, after i restart IDEA, `GrepConsole` is working fine.
